// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAdmin.Subscription.Models.Context;

#nullable disable

namespace StreamAdmin.Subscription.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20260827134501_UserSubscription")]
    partial class UserSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StreamAdmin.Subscription.Models.UserSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sus_billing_cycle");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sus_cancelled_at");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sus_next_billing_date");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("sus_notes");

                    b.Property<long?>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("sus_plan_id");

                    b.Property<long>("PlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("sus_platform_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sus_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sus_status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sus_id");

                    b.HasKey("Id");

                    b.ToTable("stream_user_subscriptions");
                });

            modelBuilder.Entity("StreamAdmin.Subscription.Models.UserSubscription", b =>
                {
                    b.OwnsOne("StreamAdmin.Subscription.Models.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<long>("UserSubscriptionId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("sus_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("sus_currency");

                            b1.HasKey("UserSubscriptionId");

                            b1.ToTable("stream_user_subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("UserSubscriptionId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
