// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAdmin.Catalog.Models.Context;

#nullable disable

namespace StreamAdmin.Catalog.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20260806000050_StreamPlatformData")]
    partial class StreamPlatformData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowsDownloads")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_allowsdownloads");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("spln_currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("spln_description");

                    b.Property<bool>("HasAds")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_hasads");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_isactive");

                    b.Property<string>("MaximumResolution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("spln_maximumresolution");

                    b.Property<int?>("MaximumScreens")
                        .HasColumnType("int")
                        .HasColumnName("spln_maximumscreens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("spln_name");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("spln_referenceprice");

                    b.Property<long>("StreamingPlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("spln_streamingplatformid");

                    b.HasKey("Id");

                    b.HasIndex("StreamingPlatformId");

                    b.ToTable("streaming_plans");
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlatform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("sp_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sp_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("sp_name");

                    b.Property<string>("WebSiteUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sp_websiteurl");

                    b.HasKey("Id");

                    b.ToTable("stream_platforms");
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlan", b =>
                {
                    b.HasOne("StreamAdmin.Catalog.Models.StreamingPlatform", "StreamingPlatform")
                        .WithMany("Plans")
                        .HasForeignKey("StreamingPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingPlatform");
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlatform", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
