// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAdmin.Catalog.Models.Context;

#nullable disable

namespace StreamAdmin.Catalog.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20260817033618_CatalogSeedAndPlanColumnTypes")]
    partial class CatalogSeedAndPlanColumnTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowsDownloads")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_allowsdownloads");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("spln_currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("spln_description");

                    b.Property<bool>("HasAds")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_hasads");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("spln_isactive");

                    b.Property<string>("MaximumResolution")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("spln_maximumresolution");

                    b.Property<int?>("MaximumScreens")
                        .HasColumnType("int")
                        .HasColumnName("spln_maximumscreens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("spln_name");

                    b.Property<decimal>("ReferencePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("spln_referenceprice");

                    b.Property<long>("StreamingPlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("spln_streamingplatformid");

                    b.HasKey("Id");

                    b.HasIndex("StreamingPlatformId");

                    b.ToTable("streaming_plans");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano com anúncios e resolução Full HD.",
                            HasAds = true,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Padrão com anúncios",
                            ReferencePrice = 20.90m,
                            StreamingPlatformId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano sem anúncios e resolução Full HD.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Padrão",
                            ReferencePrice = 44.90m,
                            StreamingPlatformId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano sem anúncios com resolução 4K e HDR.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "4K + HDR",
                            MaximumScreens = 4,
                            Name = "Premium",
                            ReferencePrice = 59.90m,
                            StreamingPlatformId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            AllowsDownloads = false,
                            Currency = "BRL",
                            Description = "Plano com anúncios e resolução Full HD.",
                            HasAds = true,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Padrão com anúncios",
                            ReferencePrice = 29.90m,
                            StreamingPlatformId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano sem intervalos comerciais e resolução Full HD.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Padrão",
                            ReferencePrice = 49.90m,
                            StreamingPlatformId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano sem intervalos comerciais com resolução 4K UHD e HDR.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "4K UHD/HDR",
                            MaximumScreens = 4,
                            Name = "Premium",
                            ReferencePrice = 69.90m,
                            StreamingPlatformId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            AllowsDownloads = false,
                            Currency = "BRL",
                            Description = "Plano com anúncios e resolução Full HD.",
                            HasAds = true,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Básico com anúncios",
                            ReferencePrice = 29.90m,
                            StreamingPlatformId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano com resolução Full HD e downloads para visualização offline.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "Full HD",
                            MaximumScreens = 2,
                            Name = "Standard",
                            ReferencePrice = 39.90m,
                            StreamingPlatformId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano com resolução 4K UHD e downloads para visualização offline.",
                            HasAds = false,
                            IsActive = true,
                            MaximumResolution = "4K UHD",
                            MaximumScreens = 4,
                            Name = "Platinum",
                            ReferencePrice = 55.90m,
                            StreamingPlatformId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            AllowsDownloads = true,
                            Currency = "BRL",
                            Description = "Plano Amazon Prime com acesso ao catálogo do Prime Video.",
                            HasAds = true,
                            IsActive = true,
                            MaximumResolution = "4K UHD",
                            MaximumScreens = 3,
                            Name = "Amazon Prime",
                            ReferencePrice = 19.90m,
                            StreamingPlatformId = 4L
                        });
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlatform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("sp_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sp_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("sp_name");

                    b.Property<string>("WebSiteUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sp_websiteurl");

                    b.HasKey("Id");

                    b.ToTable("stream_platforms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Serviço de streaming de filmes, séries e jogos.",
                            IsActive = true,
                            Name = "Netflix",
                            WebSiteUrl = "https://www.netflix.com/br/"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Serviço de streaming da Disney, Pixar, Marvel, Star Wars, National Geographic e ESPN.",
                            IsActive = true,
                            Name = "Disney+",
                            WebSiteUrl = "https://www.disneyplus.com/pt-br"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Serviço de streaming da Warner Bros. Discovery.",
                            IsActive = true,
                            Name = "HBO Max",
                            WebSiteUrl = "https://www.max.com/br/pt"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Serviço de streaming incluído na assinatura Amazon Prime.",
                            IsActive = true,
                            Name = "Prime Video",
                            WebSiteUrl = "https://www.primevideo.com/"
                        });
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlan", b =>
                {
                    b.HasOne("StreamAdmin.Catalog.Models.StreamingPlatform", "StreamingPlatform")
                        .WithMany("Plans")
                        .HasForeignKey("StreamingPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingPlatform");
                });

            modelBuilder.Entity("StreamAdmin.Catalog.Models.StreamingPlatform", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
